<?php

declare(strict_types=1);

namespace App\Tests\Service\Reporter;


use App\Service\Reporter\FileImportReporter;
use PHPUnit\Framework\TestCase;

class FileImportReporterTest extends TestCase
{
    /**
     * @var FileImportReporter
     */
    private $reporter;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->reporter = new FileImportReporter();
    }

    public function testGettersAndSetters(): void
    {

    }
}