<?php

declare(strict_types=1);

namespace App\Tests\Service\Tool;

use App\Service\Tool\FileExtensionFinder;
use PHPUnit\Framework\TestCase;

class FileExtensionFinderTest extends TestCase
{
    /**
     * @var FileExtensionFinder
     */
    private $extensionFinder;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->extensionFinder = new FileExtensionFinder();
    }

    /**
     *
     */
    public function testFindFileExtensionFromPath(): void
    {
        self::assertSame('data', $this->extensionFinder->findFileExtensionFromPath('testfile.data'));
    }

}