<?php

declare(strict_types=1);

namespace App\Tests\Service\ImportTool;

use App\Entity\Product;
use App\Repository\ProductRepository;
use App\Service\Reporter\FileImportReporter;
use App\Service\ImportTool\FileDataValidator;
use PHPUnit\Framework\TestCase;
use function foo\func;

class FileDataValidatorTest extends TestCase
{
    /**
     * @var FileDataValidator
     */
    private $validator;

    /**
     * @var array
     */
    private $dataToValidate;

    /**
     * @var FileImportReporter
     */
    private $reporter;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $mockProductRepository = $this->getMockBuilder(ProductRepository::class)
                                ->disableOriginalConstructor()
                                ->getMock();

        $mockProductRepository->expects($this->any())->method('findOneBy')->willReturnCallback(
            function ($code){
                $servername = "localhost";
                $username = "admin";
                $password = "Qwerty@123";
                $dbname = "importTest";

                $conn = mysqli_connect($servername, $username, $password, $dbname);
                if (!$conn) {
                    die("Connection failed: " . mysqli_connect_error());
                };

                $sql = "SELECT * FROM tblProduct WHERE strProductCode = P0001";

                return mysqli_query($conn, $sql);

                mysqli_close($conn);
            }
        );

        $this->reporter = new FileImportReporter();

        $this->validator = new FileDataValidator($this->reporter, $mockProductRepository);
    }

    /**
     * @param $name
     * @param $description
     * @param $code
     * @param $discontinued
     * @param $stock
     * @param $cost
     *
     * @param $result
     * @param $message
     * @dataProvider provideInvalidDataToValidate
     */
    public function testValidateInvalidProducts($name, $description, $code, $discontinued, $stock, $cost, $result, $message)
    {
        $this->dataToValidate[FileDataValidator::PRODUCT_NAME_COLUMN] = $name;
        $this->dataToValidate[FileDataValidator::PRODUCT_DESCRIPTION_COLUMN] = $description;
        $this->dataToValidate[FileDataValidator::PRODUCT_CODE_COLUMN] = $code;
        $this->dataToValidate[FileDataValidator::PRODUCT_STOCK_COLUMN] = $stock;
        $this->dataToValidate[FileDataValidator::PRODUCT_COST_COLUMN] = $cost;
        $this->dataToValidate[FileDataValidator::PRODUCT_DISCONTINUED_COLUMN] = $discontinued;

        $isValid = $this->validator->validate($this->dataToValidate);

        $this->assertSame($isValid, $result);
        if ($result != true) {
        $isMessage = false;
            foreach ($this->reporter->getMessages() as $msg){
                if ($message === $msg){
                    $isMessage = true;
                }
            }
            $this->assertSame(true, $isMessage);
        }
    }

    public function provideInvalidDataToValidate()
    {
        return[
            [null, 'description-1', 'P00011000', '', 9, 100, false, 'Invalid product name'],
            ['Some name', null, 'P000250', 'yes', 9, 100, false, 'Invalid product description'],
            ['Some Other name', 'description-1.1', null, 'yes', 9, 100, false, 'Invalid product code'],
            ['Invalid Product', 'because of cost and stock', 'P0003000', '', 4, 3, false, 'Stock and cost are less than rule'],
            ['Tv', 'Desc.', 'P000400000', '', 0, 120000, false, 'Cost is more than rule'],
            ['name0', 'description0', 'P00055', 'yes', 9, 100, true, null],
            ['name1', 'description1', 'P000666', '', 5, 11, true, null],
            ['Valid Product', 'Descr.', 'P00070', '', 20, 10,true, null],
            ['name2', 'description2', 'P00088', '', 90, 10, true, null],
            ['name3', 'description3', 'P00099', 'no', 131, 115, true, null],
            ['name4', 'description4', 'P0001', 'no', 131, 115, false, 'This product already exists'],
        ];
    }
}