<?php

declare(strict_types=1);

namespace App\Tests\Service\ImportTool;

use App\Repository\ProductRepository;
use App\Service\Reporter\FileImportReporter;
use App\Service\ImportTool\ProductImportFileValidator;
use PHPUnit\Framework\TestCase;

class ProductImportFileValidatorTest extends TestCase
{
    /**
     * @var ProductImportFileValidator
     */
    private $validator;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $mockReporter = $this->getMockBuilder(FileImportReporter::class)->getMock();

        $mockProductRepository = $this->getMockBuilder(ProductRepository::class)->disableOriginalConstructor()->getMock();

        $this->validator = new ProductImportFileValidator($mockReporter, $mockProductRepository);
    }

    public function testValidate()
    {
        $isValidData = $this->validator->validate([
            'Product Name' => 'Action',
            'Product Description' => 'he is stupid but cute',
            'Product Code' => 'JustCode0000',
            'Stock' => 100,
            'Cost in GBP' => 25,
            'Discontinued' => 'yes'
        ]);

        $this->assertSame(true, $isValidData);
    }
}